include:
  - 'docker-compose.base.yml'
services:
  discord:
    image: docker.degrendel.com/elusivebot/discord:latest
    container_name: 'elusivebot.discord'
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka
    environment:
      - "DISCORD_KAFKA_BOOTSTRAP=elusivebot.kafka:9092"
      - "DISCORD_KAFKA_PRODUCERTOPIC=messages-input"
      - "DISCORD_KAFKA_CONSUMERTOPIC=messages-output"
    volumes:
      - "${BASE_DIR:?base dir must be set}/discord/config:/config"
  pattern-match:
    image: docker.degrendel.com/elusivebot/pattern-match:latest
    container_name: 'elusivebot.pattern.match'
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka
    environment:
      - "PATTERNMATCH_KAFKA_BOOTSTRAP=elusivebot.kafka:9092"
      - "PATTERNMATCH_KAFKA_PRODUCERTOPIC=messages-output"
      - "PATTERNMATCH_KAFKA_CONSUMERTOPIC=messages-input"
