services:
  kafka:
    image: docker.io/bitnami/kafka:3.6
    container_name: elusivebot.kafka
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - "${BASE_DIR:?base dir must be set}/kafka/data:/bitnami/kafka"
      - "${BASE_DIR}/kafka/bin//run-init-kafka-topics.sh:/docker-entrypoint-initdb.d/run-init-kafka-topics.sh:ro"
      - "${BASE_DIR}/kafka/bin/init-kafka-topics.sh:/init-kafka-topics.sh:ro"
    healthcheck:
      test: /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 20s
    networks:
      - kafka
networks:
  kafka: {}

