include:
  - 'docker-compose.base.yml'
services:
  discord:
    image: elusivebot/discord:latest
    container_name: 'elusivebot.discord'
    depends_on: [ kafka ]
    networks:
      - kafka
    environment:
      - "DISCORD_KAFKA_BOOTSTRAP=elusivebot.kafka:9092"
      - "DISCORD_KAFKA_PRODUCER=messages-input"
      - "DISCORD_KAFKA_CONSUMER=messages-output"
    env_file:
      - .discord.prod.env
  pattern-match:
    image: elusivebot/pattern-match:latest
    container_name: 'elusivebot.pattern.match'
    depends_on: [ kafka ]
    networks:
      - kafka
    environment:
      - "PATTERNMATCH_KAFKA_BOOTSTRAP=elusivebot.kafka:9092"
      - "PATTERNMATCH_KAFKA_PRODUCER=messages-output"
      - "PATTERNMATCH_KAFKA_CONSUMER=messages-input"
