version: '3.8'
include:
  - 'docker-compose.base.yml'
services:
  direct:
    image: elusivebot-direct:latest
    ports:
      - "8001:8001"
    container_name: 'elusivebot.direct'
    networks:
      - kafka
    environment:
      - "DIRECT_KAFKA_HOST=elusivebot.kafka:9092"
      - "DIRECT_LISTEN_PORT=8001"
      - "DIRECT_LISTEN_HOST=0.0.0.0"
