include:
  - 'docker-compose.base.yml'
services:
  direct:
    image: docker.degrendel.com/elusivebot/direct:latest
    ports:
      - "8001:8001"
    container_name: 'elusivebot.direct'
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka
    environment:
      - "DIRECT_KAFKA_BOOTSTRAP=elusivebot.kafka:9092"
      - "DIRECT_KAFKA_PRODUCERTOPIC=messages-input"
      - "DIRECT_KAFKA_CONSUMERTOPIC=messages-output"
      - "DIRECT_LISTEN_PORT=8001"
      - "DIRECT_LISTEN_HOST=0.0.0.0"
  pattern-match:
    image: docker.degrendel.com/elusivebot/pattern-match:latest
    container_name: 'elusivebot.pattern.match'
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka
    environment:
      - "PATTERNMATCH_KAFKA_BOOTSTRAP=elusivebot.kafka:9092"
      - "PATTERNMATCH_KAFKA_PRODUCERTOPIC=messages-output"
      - "PATTERNMATCH_KAFKA_CONSUMERTOPIC=messages-input"
  docs:
    image: docker.degrendel.com/elusivebot/docs:latest
    container_name: "elusivebot.docs"
    ports:
     - "8080:8080"
    environment:
     - NGINX_PORT=8080
  watchtower:
    image: containrrr/watchtower
    container_name: "elusivebot.watchtower"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 60
