version: '3.8'
services:
  redis:
    image: redis:7
    container_name: elusivebot.redis
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - type: bind
        source: /srv/elusivebot/redis/data
        target: /data
    networks:
      - redis
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
    container_name: elusivebot.rabbitmq
    networks:
      - rabbitmq
networks:
  redis: {}
  rabbitmq: {}

